"""External provider contracts used by the backend and Agent."""

from .garment_masker import (
    GarmentMask,
    GarmentMaskContractError,
    GarmentMaskInput,
    GarmentMaskProviderError,
    GarmentMaskUnavailableError,
    GarmentMasker,
    GarmentMaskerProvider,
    HttpxGarmentMaskHttpClient,
)
from .measurement_line import (
    MEASUREMENT_LINE_JSON_SCHEMA,
    MeasurementEndpoints,
    MeasurementImage,
    MeasurementLineContractError,
    MeasurementLineInput,
    MeasurementLineProvider,
    NormalizedPoint,
    ResponsesMeasurementLineProvider,
    validate_measurement_endpoints,
)
from .runtime import (
    FixtureVisionGuidanceProvider,
    LiveAnalyzer,
    LiveVisionGuidanceProvider,
    ProviderInference,
    ProviderUnavailableError,
    create_provider_inference,
    create_vision_guidance_provider,
    guidance_input_from_frame,
)
from .vision_guidance import (
    EncodedImage,
    GuidanceCode,
    GuidanceContractError,
    GuidanceInput,
    GuidanceShot,
    VisionDecision,
    VisionGuidanceProvider,
)
from .shot_assessor import (
    AssessmentImage,
    ResponsesShotAssessor,
    ShotAssessment,
    ShotAssessmentContractError,
    ShotAssessor,
    ShotAssessorInput,
    validate_shot_assessment,
)
from .shot_assessor_factory import FixtureShotAssessor, create_shot_assessor


__all__ = [
    "AssessmentImage",
    "EncodedImage",
    "FixtureShotAssessor",
    "FixtureVisionGuidanceProvider",
    "GarmentMask",
    "GarmentMaskContractError",
    "GarmentMaskInput",
    "GarmentMaskProviderError",
    "GarmentMaskUnavailableError",
    "GarmentMasker",
    "GarmentMaskerProvider",
    "GuidanceCode",
    "GuidanceContractError",
    "GuidanceInput",
    "GuidanceShot",
    "LiveAnalyzer",
    "LiveVisionGuidanceProvider",
    "MEASUREMENT_LINE_JSON_SCHEMA",
    "MeasurementEndpoints",
    "MeasurementImage",
    "MeasurementLineContractError",
    "MeasurementLineInput",
    "MeasurementLineProvider",
    "NormalizedPoint",
    "ProviderInference",
    "ProviderUnavailableError",
    "ResponsesMeasurementLineProvider",
    "ResponsesShotAssessor",
    "ShotAssessment",
    "ShotAssessmentContractError",
    "ShotAssessor",
    "ShotAssessorInput",
    "VisionDecision",
    "VisionGuidanceProvider",
    "create_provider_inference",
    "create_shot_assessor",
    "create_vision_guidance_provider",
    "guidance_input_from_frame",
    "HttpxGarmentMaskHttpClient",
    "validate_measurement_endpoints",
    "validate_shot_assessment",
]
